### PR TITLE
WIP: checkout what's going on upstream

### PR DESCRIPTION
**Pull request by GitMensch**
... just exploration for now

### CODE REVIEW

**Comment by GitMensch** [comment]
@paulcarroty: Do you think a one-time manual merge would be useful? if not, should the README to be adjusted dropping that notice?

If we do a merge then we should rename master to main to be similar to upstream (and because the adjusted branch name is referenced in all the updated files).

In any case it seems like the dependencies should be build using a different dockerfile, see https://github.com/jeanp413/open-remote-ssh/issues/24.

**Comment by paulcarroty** [comment]
LGTM, let's sync with MS images. @daiyam?

**Comment by daiyam** [comment]
It hasn't been work on so it can be merged...

**Comment by GitMensch** [comment]
At the scale of those changes we may even consider to include upstream as "main"; renaming the current "master" to "old-master", then either adjust the MS version "from scratch" or merge the necessary pieces from "old-master" into "main".

**Comment by daiyam** [comment]
It has been done in #14

**Comment by GitMensch** [comment]
I think that updating to upstream is quite good - thanks for the work put into that.

The first question is of course: we're now down to 5 environments https://github.com/VSCodium/vscode-linux-build-agent/actions/runs/3284904497 (currently with centos7 arm64 broken) - do we need all of the previous 9 environments? https://github.com/VSCodium/vscode-linux-build-agent/actions/runs/2803989373 so they must be added next?

The second question is: How/when would this be used for building vscodium/vscoium-reh?

**Comment by daiyam** [comment]
We were using only 3 environments... so we don't need the extra environments

The centos7 environments are used to create an archive containing the node dependencies for `reh`. That archive is then importing into the regular build process.

**Comment by daiyam** [comment]
But there is an error when building `centos7-devtoolset8-arm64` which is direct from MS...

Edit: fixed, it needed qemu...

**Pull request closed without merging**
